Repository Leets-Official/CHIKAHAE-FE, pull requests merged in 2025-07, with the labels that each got.

#5 [Chore] Tailwind & Tokens Studio 연동 세팅
  package-lock.json
  package.json
  sd-tokens-config.js
  split-tokens.js
  src/tokens/design-tokens.json
  tailwind.config.js
  tw-tokens-config.js
Labels: ⚙ Setting, 🔧 Chore

#10 [feat] #9 토스트 컴포넌트 구현
  package.json
  src/components/ui/Toast.tsx
  src/components/ui/ToastContainer.tsx
  src/styles/index.css
  tailwind.config.js
Labels: ✨ Feature

#16 [feat] #15 Toast 컴포넌트 피드백 반영
  src/App.tsx
  src/components/ui/Toast/Toast.tsx
  src/components/ui/Toast/ToastContainer.tsx
  src/main.tsx
  src/pages/test/ToastTest.tsx
  src/styles/index.css
  tailwind.config.js
Labels: ✨ Feature

#21 [Style] #19 전역 스타일 설정
  package-lock.json
  package.json
  postcss.config.cjs
  public/fonts/NanumSquareRoundB.ttf
  public/fonts/NanumSquareRoundEB.ttf
  public/fonts/NanumSquareRoundL.ttf
  public/fonts/NanumSquareRoundR.ttf
  public/fonts/fonts.css
  sd-tokens-config.js
  split-tokens.js
  src/components/ui/Toast.tsx
  src/components/ui/ToastContainer.tsx
  src/main.tsx
  src/styles/global.css
  src/styles/index.css
  src/tokens/design-tokens.json
  tailwind.config.js
  tw-tokens-config.js
Labels: 🎨Style

#22 [Feat] #20 Nav / Text Button / Radio Button 컴포넌트 구현
  package-lock.json
  package.json
  src/App.tsx
  src/assets/images/Bell.svg
  src/assets/images/Chevron_left.svg
  src/assets/images/Chevron_right.svg
  src/assets/images/Gear.svg
  src/assets/images/cancel.svg
  src/components/RadioButton.tsx
  src/components/ui/Button/index.ts
  src/components/ui/Nav/BottomNav.tsx
  src/components/ui/Nav/TopNav.tsx
  src/components/ui/TextButton/TextButton.tsx
  src/components/ui/TextButton/TextButton.types.ts
  src/components/ui/TextButton/index.ts
  src/pages/test/AllComponentTest.tsx
  src/pages/test/NavTest.tsx
  src/pages/test/RadioButtonTest.tsx
  src/pages/test/TextButtonTest.tsx
  src/styles/global.css
  src/types/svg.d.ts
  tsconfig.json
  vite.config.ts
Labels: ✨ Feature

#29 [feat] #26 공동 컴포넌트 css 디자인 구현
  src/App.tsx
  src/assets/icons/bell.svg
  src/assets/icons/calendar.svg
  src/assets/icons/cancel.svg
  src/assets/icons/chevron_left.svg
  src/assets/icons/chevron_right.svg
  src/assets/icons/chika.svg
  src/assets/icons/gear.svg
  src/assets/icons/home.svg
  src/assets/icons/mypage.svg
  src/assets/icons/quiz.svg
  src/components/Container.tsx
  src/components/RadioButton.tsx
  src/components/ui/Button/RadioButton/RadioButton.tsx
  src/components/ui/Button/RadioButton/RadioButtonContainer.tsx
  src/components/ui/Input.tsx
  src/components/ui/Input/Input.tsx
  src/components/ui/Input/InputContainer.tsx
  src/components/ui/Nav/BottomNav.tsx
  src/components/ui/Nav/GlobalTopNav.tsx
  src/components/ui/Nav/HomeTopNav.tsx
  src/components/ui/Nav/TopNav.tsx
  src/components/ui/UserInfoForm.tsx
  src/constants/navItems.ts
  src/constants/radioOptions.ts
  src/pages/test/AllComponentTest.tsx
  src/pages/test/NavTest.tsx
  src/pages/test/RadioButtonTest.tsx
  src/pages/test/TextButtonTest.tsx
  src/styles/global.css
Labels: ✨ Feature

#41 [Feat] #40 퀴즈 / 양치 시작 페이지 UI 구현
  index.html
  src/App.tsx
  src/assets/images/brushingStart.png
  src/assets/images/quizStart.png
  src/components/ui/NoticeList.tsx
  src/constants/navItems.ts
  src/features/quiz/quizFlow/QuizSummary.tsx
  src/features/quiz/quizFlow/quizSolve/QuizBody.tsx
  src/features/quiz/quizFlow/quizSolve/QuizContent.tsx
  src/features/quiz/quizFlow/quizSolve/QuizFooter.tsx
  src/features/quiz/quizOXButton/QuizOXButton.tsx
  src/features/quiz/quizOXButton/QuizOXButton.types.ts
  src/features/quiz/quizResult/QuizResult.tsx
  src/features/quiz/quizResult/QuizResult.types.ts
  src/features/quiz/quizResult/QuizResultBlock.tsx
  src/features/quiz/quizResult/QuizResultBlock.types.ts
  src/features/quiz/quizTextButton/QuizTextButton.tsx
  src/features/quiz/quizTextButton/QuizTextButton.types.ts
  src/features/quiz/quizTitle/QuizTitle.tsx
  src/features/quiz/quizTitle/QuizTitle.types.ts
  src/features/start/StartPageTemplate.tsx
  src/pages/brushing/BrushingStartPage.tsx
  src/pages/quiz/QuizPage.tsx
  src/pages/quiz/QuizStartPage.tsx
  src/pages/quiz/StartQuizPage.tsx
Labels: ✨ Feature, 🔨 Refactor, 🔧 Chore

#43 [Fix] #42 build 시 발생하는 오류 수정
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/features/quiz/quizFlow/quizSolve/QuizContent.tsx
  src/features/signup/signupProfile.tsx
  src/types/svg.d.ts
  tsconfig.json
Labels: 🐞BugFix, 🔧 Chore

#48 [Feat] #44 퀴즈 페이지 / 알람 api 연결
  public/firebase-messaging-sw.js
  src/api/alaram/fcmTokenAPI.ts
  src/api/api.ts
  src/api/quiz/quizAPI.ts
  src/components/ui/Timer/Timer.tsx
  src/features/quiz/quizFlow/quizSolve/QuizBody.tsx
  src/features/quiz/quizFlow/quizSolve/QuizContent.tsx
  src/features/quiz/quizResult/QuizResult.tsx
  src/features/quiz/quizResult/QuizResult.types.ts
  src/pages/quiz/QuizPage.tsx
  src/pages/quiz/QuizStartPage.tsx
  src/utils/firebaseMessaging.ts
Labels: ✨ Feature, 🔨 Refactor, 📬 API

#51 [Feat] #33 home UI 구현
  src/App.tsx
  src/assets/icons/caution.svg
  src/assets/icons/homeLogo.svg
  src/assets/icons/rabbit.svg
  src/assets/icons/toothbrush.svg
  src/assets/images/background.svg
  src/components/ui/Modal/TimePickerModal.tsx
  src/components/ui/Nav/HomeTopNav.tsx
  src/constants/navItems.ts
  src/features/Home/components/BrushingSessionCard.tsx
  src/features/Home/components/BrushingSessionList.tsx
  src/features/Home/components/HomeBanner.tsx
  src/features/Home/constants/brushingSessions.ts
  src/features/Mypage/components/EditMenuItem.tsx
  src/features/Mypage/components/EditMenuList.tsx
  src/features/Mypage/constants/fieldConfig.ts
  src/pages/Home/HomePage.tsx
  src/pages/mypage/ChikaAlarmPage.tsx
  src/pages/mypage/EditFieldPage.tsx
  src/pages/mypage/EditProfilePage.tsx
  src/pages/mypage/MyPage.tsx
  src/styles/global.css
Labels: ✨ Feature, 🎨Style

#49 [Feat] #47 로그인/회원가입 화면 디자인 구현
  src/assets/icons/signupMainCharacter.svg
  src/assets/icons/signupSideLogo.svg
  src/assets/images/signupBackground.svg
  src/pages/auth/LoginPage.tsx
Labels: ✨ Feature

#60 [Feat] #59 간편 로그인 페이지 기능 구현
  src/assets/icons/authCharacterRandom1.svg
  src/assets/icons/authCharacterRandom2.svg
  src/assets/icons/authCharacterRandom3.svg
  src/components/ui/Timer/Timer.tsx
  src/components/ui/Timer/Timer.types.ts
  src/constants/characterMessages.ts
  src/pages/auth/LoginPage.tsx
  src/pages/auth/SignupPage.tsx
  src/pages/test/AnimationTest.tsx
Labels: ✨ Feature, 🔨 Refactor, 🎨Style

#57 [Feat] #45 로그인/회원가입 api 연결
  src/api/alarm/fcmTokenAPI.ts
  src/api/auth/kakaoAPI.ts
  src/api/auth/signupAPI.ts
  src/components/ui/UserInfoForm.tsx
  src/constants/radioOptions.ts
  src/features/signup/SignupGuardianForm.tsx
  src/features/signup/SignupInfo.tsx
  src/features/signup/SignupProfile.tsx
  src/pages/auth/KakaoCallback.tsx
  src/pages/auth/SignupPage.tsx
Labels: ✨ Feature, 📬 API

#64 [Style] #62 BottomNav ui 수정
  src/assets/icons/chika.svg
  src/assets/icons/home.svg
  src/assets/icons/mypage.svg
  src/assets/icons/quiz.svg
  src/components/ui/Nav/BottomNav.tsx
Labels: 🎨Style
