Repository Leets-Official/CHIKAHAE-FE, pull requests merged in 2025-08, with the labels that each got.

#67 [Style] #56 홈/퀴즈 UI 수정
  src/api/quiz/quizAPI.ts
  src/assets/images/background.svg
  src/assets/images/home_background.svg
  src/components/ui/Nav/BottomNav.tsx
  src/features/Home/homeBanner/HomeBanner.tsx
  src/features/start/StartPageTemplate.tsx
  src/pages/Home/HomePage.tsx
Labels: 🔨 Refactor, 🎨Style

#70 [Feat] #68 로그인/회원가입 api 수정사항 반영
  src/App.tsx
  src/api/api.ts
  src/api/auth/kakaoAPI.ts
  src/api/auth/signupAPI.ts
  src/api/fcm/fcmAPI.ts
  src/assets/terms/optional-privacy.md
  src/assets/terms/required-privacy.md
  src/assets/terms/required-terms.md
  src/components/ui/Button/KakaoLoginButton.tsx
  src/features/alarm/fcm.ts
  src/features/login/RandomCharcterMessage.tsx
  src/features/login/TermsList.tsx
  src/features/signup/SignupComplete.tsx
  src/features/signup/SignupGuardianForm.tsx
  src/features/signup/SignupGuardianIntro.tsx
  src/features/signup/SignupInfo.tsx
  src/features/signup/SignupProfile.tsx
  src/hooks/useAgreementParams.ts
  src/main.tsx
  src/pages/Home/HomePage.tsx
  src/pages/auth/KakaoCallback.tsx
  src/pages/auth/LoginPage.tsx
  src/pages/auth/SignupPage.tsx
  src/pages/auth/terms/TermsPage.tsx
  src/utils/firebaseMessaging.ts
Labels: ✨ Feature, 🔨 Refactor, 🎨Style, 📬 API

#72 [Feat] #71 애니메이션 시작/정지 버튼 컴포넌트 구현
  src/assets/icons/pauseButton.svg
  src/assets/icons/playButton.svg
  src/components/ui/Button/AnimationButton.tsx
  src/components/ui/Button/KakaoLoginButton.tsx
  src/components/ui/Timer/Timer.tsx
  src/components/ui/Timer/Timer.types.ts
  src/pages/test/AnimationTest.tsx
Labels: ✨ Feature

#73 [Feat] #63 마이페이지 / 알람 / 미션 api 연결
  src/App.tsx
  src/api/fcm/fcmAPI.ts
  src/api/fcm/fcmTokenAPI.ts
  src/api/home/missionAPI.ts
  src/api/myPage/alarmAPI.ts
  src/api/myPage/authAPI.ts
  src/api/myPage/profileAPI.ts
  src/components/ui/Modal/Modal.tsx
  src/components/ui/Modal/TimePickerModal.tsx
  src/components/ui/Nav/GlobalTopNav.tsx
  src/components/ui/TimePicker/ScrollColumn.tsx
  src/components/ui/TimePicker/TimePicker.tsx
  src/components/ui/Toggle/Toggle.tsx
  src/constants/terms.ts
  src/features/Mypage/alarm/AlarmButton.tsx
  src/features/Mypage/alarm/alarmSet/AlarmContent.tsx
  src/features/Mypage/alarm/alarmSet/AlarmList.tsx
  src/features/Mypage/alarm/alarmSet/AlarmToggle.tsx
  src/features/Mypage/components/ChikaAlarm.tsx
  src/features/Mypage/components/ChikaAlarmButton.tsx
  src/features/Mypage/components/UserInfoList.tsx
  src/features/Mypage/menu/MenuItem.tsx
  src/features/Mypage/menu/MenuList.tsx
  src/features/Mypage/userInfo/UserInfoList.tsx
  src/features/Mypage/userProfile/ProfileSection.tsx
  src/features/alarm/fcm.ts
  src/features/alarm/registerFcmToken.ts
  src/features/quiz/quizFlow/quizSolve/QuizFooter.tsx
  src/hooks/queries/useAlarmQuery.ts
  src/hooks/useAgreementParams.ts
  src/hooks/useSelectedAlarm.ts
  src/pages/Home/HomePage.tsx
  src/pages/mypage/AlarmPage.tsx
  src/pages/mypage/ChikaAlarmPage.tsx
  src/pages/mypage/EditProfilePage.tsx
  src/pages/mypage/MyPage.tsx
  src/pages/mypage/UserInfoPage.tsx
  src/pages/quiz/QuizPage.tsx
  src/styles/global.css
  src/utils/fcmTokenManager.ts
  src/utils/firebaseMessaging.ts
  src/utils/formatSendTime.ts
  src/utils/notification.ts
  vite.config.ts
Labels: ✨ Feature, 🔨 Refactor, 📬 API

#78 [refactor] #77 홈 리팩토링
  src/components/ui/Nav/HomeTopNav.tsx
  src/features/Home/homeBanner/HomeBanner.tsx
  src/features/Home/todayMission/BrushingSessionList.tsx
  src/pages/Home/HomePage.tsx
Labels: 🔨 Refactor, 🎨Style

#82 [Style] #81 화면 ui 수정
  src/components/ui/Toast/Toast.tsx
  src/features/Home/homeBanner/HomeBanner.tsx
  src/features/quiz/quizFlow/quizSolve/QuizContent.tsx
  src/features/quiz/quizResult/QuizResult.tsx
  src/features/quiz/quizTitle/QuizTitle.tsx
  src/features/start/StartPageTemplate.tsx
  src/pages/Home/HomePage.tsx
  src/pages/mypage/AlarmPage.tsx
  src/pages/mypage/EditProfilePage.tsx
  src/pages/mypage/MyPage.tsx
  src/pages/quiz/QuizPage.tsx
  src/pages/test/AnimationTest.tsx
Labels: 🎨Style

#84 [Fix] #83 배포 중 발생하는 에러 수정
  package.json
  src/features/quiz/quizOXButton/QuizOXButton.tsx
Labels: 🐞BugFix, 🌏 Deploy

#85 [fix] #83 파일명 오타 수정
  src/features/quiz/quizResult/QuizResultBlock.tsx
Labels: 🐞BugFix, 🌏 Deploy

#86 fix: svg 파일 깨짐 문제 수정
  src/components/ui/Button/KakaoLoginButton.tsx
Labels: 🐞BugFix

#88 [Fix] #83 vercel.json 수정
  src/features/signup/SignupComplete.tsx
  src/features/signup/SignupGuardianForm.tsx
  src/features/signup/SignupGuardianIntro.tsx
  src/features/signup/SignupInfo.tsx
  src/features/signup/SignupProfile.tsx
  vercel.json
Labels: 🐞BugFix

#89 Fix/#83 build fix deploy set
  src/features/signup/SignupInfo.tsx
  src/pages/auth/SignupPage.tsx
Labels: 🐞BugFix

#91 [Fix] #83 회원가입 페이지에서 카카오 토큰 유실 시 localStorage로 복구
  src/pages/auth/KakaoCallback.tsx
  src/pages/auth/SignupPage.tsx
Labels: 🐞BugFix

#94 [Feat] #80 애니메이션 ui 구현 및 api 연결
  public/bgm/animation_bgm.mp3
  public/fonts/CookieRunBlack.ttf
  src/App.tsx
  src/assets/icons/pauseButton.svg
  src/assets/icons/pause_icon.svg
  src/assets/icons/playButton.svg
  src/assets/icons/play_icon.svg
  src/assets/images/animation_background.svg
  src/assets/images/backgroundImage.svg
  src/assets/lottie/brushing_dog.json
  src/assets/lottie/brushing_rabbit.json
  src/assets/lottie/brushing_squirrel.json
  src/assets/lottie/defend_dog.json
  src/assets/lottie/defend_rabbit.json
  src/assets/lottie/defend_squirrel.json
  src/components/ui/Button/AnimationButton.tsx
  src/components/ui/CoinRewardResult.tsx
  src/components/ui/Timer/Timer.tsx
  src/constants/counterdownText.ts
  src/constants/tips.ts
  src/features/brushing/BrushingAnimation.tsx
  src/features/brushing/BrushingHeader.tsx
  src/features/brushing/BrushingResult.tsx
  src/features/brushing/BrushingTip.tsx
  src/features/brushing/ExitConfirmModal.tsx
  src/main.tsx
  src/pages/brushing/BrushingPage.tsx
  src/pages/brushing/BrushingStartPage.tsx
  src/pages/test/AnimationTest.tsx
  src/styles/fonts.css
  src/styles/global.css
  src/utils/getNextAnimationMission.ts
  tailwind.config.js
Labels: ✨ Feature, 🎨Style, 📬 API

#102 [Fix] #83 애니메이션 로직 수정
  src/features/brushing/BrushingAnimation.tsx
  src/features/brushing/BrushingResult.tsx
  src/pages/brushing/BrushingPage.tsx
Labels: 🐞BugFix

#103 [Chore] #83 favicon 설정
  index.html
  src/assets/icons/profileImage.svg
  src/features/signup/SignupProfile.tsx
Labels: 🔧 Chore

#104 [Fix] #83 배포 오류 수정
  src/api/api.ts
  src/components/ui/Button/RadioButton/RadioButton.tsx
  src/components/ui/Button/RadioButton/RadioButtonContainer.tsx
  src/components/ui/Input/DateInput.tsx
  src/components/ui/Input/InputContainer.tsx
  src/components/ui/Timer/Timer.tsx
  src/constants/characterMessages.ts
  src/features/brushing/BrushingResult.tsx
  src/features/login/RandomCharcterMessage.tsx
  src/features/signup/SignupComplete.tsx
  src/features/signup/SignupGuardianForm.tsx
  src/features/signup/SignupGuardianIntro.tsx
  src/features/signup/SignupInfo.tsx
  src/features/signup/SignupProfile.tsx
  src/main.tsx
Labels: 🎨Style, 📬 API

#107 [Fix] #83 타이머 프로그레스바가 고정되지 않는 이슈 수정
  src/components/ui/Timer/Timer.tsx
Labels: 🐞BugFix

#108 [Fix] #83 퀴즈페이지 치카 코인 최종 획득 수 수정
  src/pages/quiz/QuizPage.tsx
Labels: 🐞BugFix

#110 [Fix] #83 코인 보상 수 수정
  src/pages/quiz/QuizPage.tsx
Labels: 🐞BugFix
